In [23]:
import pandas as pd

In [24]:
from google.colab import files
uploaded = files.upload()

Saving loan_approval_dataset.csv to loan_approval_dataset.csv

In [48]:
df = pd.read_csv("loan_approval_dataset.csv")

In [49]:
df.columns = df.columns.str.strip()

df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [50]:
df.shape

(4269, 13)

In [51]:
df.describe()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
count,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4.269000e+03,4.269000e+03
mean,2135.000000,2.498712,5.059124e+06,1.513345e+07,10.900445,599.936051,7.472617e+06,4.973155e+06,1.512631e+07,4.976692e+06
std,1232.498479,1.695910,2.806840e+06,9.043363e+06,5.709187,172.430401,6.503637e+06,4.388966e+06,9.103754e+06,3.250185e+06
min,1.000000,0.000000,2.000000e+05,3.000000e+05,2.000000,300.000000,-1.000000e+05,0.000000e+00,3.000000e+05,0.000000e+00
25%,1068.000000,1.000000,2.700000e+06,7.700000e+06,6.000000,453.000000,2.200000e+06,1.300000e+06,7.500000e+06,2.300000e+06
50%,2135.000000,3.000000,5.100000e+06,1.450000e+07,10.000000,600.000000,5.600000e+06,3.700000e+06,1.460000e+07,4.600000e+06
75%,3202.000000,4.000000,7.500000e+06,2.150000e+07,16.000000,748.000000,1.130000e+07,7.600000e+06,2.170000e+07,7.100000e+06
max,4269.000000,5.000000,9.900000e+06,3.950000e+07,20.000000,900.000000,2.910000e+07,1.940000e+07,3.920000e+07,1.470000e+07

In [52]:
df.isnull()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,False,False,False,False,False,False,False,False,False,False,False,False,False
4265,False,False,False,False,False,False,False,False,False,False,False,False,False
4266,False,False,False,False,False,False,False,False,False,False,False,False,False
4267,False,False,False,False,False,False,False,False,False,False,False,False,False
4268,False,False,False,False,False,False,False,False,False,False,False,False,False

In [53]:
df.isnull().sum()

loan_id                     0
no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

In [73]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["education"] = le.fit_transform(df["education"])
df["self_employed"] = le.fit_transform(df["self_employed"])
df["loan_status"] = le.fit_transform(df["loan_status"])

df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0
1,2,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1
2,3,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1
3,4,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1
4,5,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1

In [74]:
X = df[[
    "income_annum",
    "loan_amount",
    "cibil_score",
    "education",
    "self_employed"
]]

In [75]:
sample = [[income, loan_amount, credit_score, education, employment]]

prediction = model.predict(sample)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

In [76]:
income = float(input("Enter Applicant Income: "))
loan_amount = float(input("Enter Loan Amount: "))
credit_score = int(input("Enter Credit Score (300-900): "))
education = int(input("Graduate? (1 = Yes, 0 = No): "))
employment = int(input("Self Employed? (1 = Yes, 0 = No): "))



if (income >= 500000 and
    loan_amount <= 2000000 and
    credit_score >= 700 and
    education == 1 and
    employment == 1):

    print("Loan Approved")

else:
    print("Loan Rejected")

Enter Applicant Income: 86966
Enter Loan Amount: 878787
Enter Credit Score (300-900): 233
Graduate? (1 = Yes, 0 = No): 1
Self Employed? (1 = Yes, 0 = No): 0
Loan Rejected

In [77]:
prediction = model.predict(X_test_encoded)

accuracy = accuracy_score(y_test, prediction)

print("Accuracy:", accuracy * 100)

Accuracy: 94.73067915690866

In [59]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score

In [67]:
X = df[[
    "income_annum",
    "loan_amount",
    "cibil_score",
    "education",
    "self_employed"
]]

y = df["loan_status"]

In [68]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd


X_train_encoded = X_train.copy()

# Initialize LabelEncoders for education and self_employed columns
# These encoders will learn the mapping from the current X_train data.
le_education = LabelEncoder()
le_self_employed = LabelEncoder()

# Apply Label Encoding to the categorical columns in X_train_encoded
X_train_encoded['education'] = le_education.fit_transform(X_train_encoded['education'])
X_train_encoded['self_employed'] = le_self_employed.fit_transform(X_train_encoded['self_employed'])

model = ExtraTreesClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train_encoded, y_train)

ExtraTreesClassifier(random_state=42)

In [70]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd


X_test_encoded = X_test.copy()

le_self_employed_test = LabelEncoder()


X_test_encoded['education'] = le_education_test.fit_transform(X_test_encoded['education'])
X_test_encoded['self_employed'] = le_self_employed_test.fit_transform(X_test_encoded['self_employed'])

prediction = model.predict(X_test_encoded)

accuracy = accuracy_score(y_test, prediction)

print("Accuracy:", accuracy * 100)

Accuracy: 94.73067915690866

In [71]:
income = float(input("Enter Applicant Income: "))
loan_amount = float(input("Enter Loan Amount: "))
credit_score = int(input("Enter Credit Score (300-900): "))
education = int(input("Graduate? (1 = Yes, 0 = No): "))
employment = int(input("Self Employed? (1 = Yes, 0 = No): "))

if (income >= 500000 and
    loan_amount <= 2000000 and
    credit_score >= 700 and
    education == 1 and
    employment == 1):

    print("Loan Approved")

else:
    print("Loan Rejected")

Enter Applicant Income: 67788
Enter Loan Amount: 7676776
Enter Credit Score (300-900): 666
Graduate? (1 = Yes, 0 = No): 0
Self Employed? (1 = Yes, 0 = No): 0
Loan Rejected