In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
from google.colab import files
uploaded=files.upload()

Saving mtcars.csv to mtcars.csv

In [4]:
dataset=pd.read_csv('/content/mtcars.csv')

In [5]:

dataset.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     object
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [7]:
dataset.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [8]:
dataset.isnull().sum()

model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

In [10]:
# Drop target column
X = dataset.drop("mpg", axis=1)
y = dataset["mpg"]

from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Drop non numeric column (example: model)
train_X_numeric = train_X.drop("model", axis=1)
test_X_numeric = test_X.drop("model", axis=1)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

train_X_numeric = scaler.fit_transform(train_X_numeric)
test_X_numeric = scaler.transform(test_X_numeric)

from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(train_X_numeric, train_y)

print(reg.score(train_X_numeric, train_y))
print(reg.score(test_X_numeric, test_y))

0.8750483703126839
0.7466453084791005

In [11]:
X=dataset.drop("mpg",axis=1)
y=dataset["mpg"]

from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_X_numeric = scaler.fit_transform(train_X_numeric)
test_X_numeric = scaler.transform(test_X_numeric)

from sklearn.linear_model import LinearRegression
reg = LinearRegression()
train_X_numeric = train_X.drop('model', axis=1)
test_X_numeric = test_X.drop('model', axis=1)
reg.fit(train_X_numeric, train_y)

reg.score(train_X_numeric, train_y)

reg.score(test_X_numeric, test_y)

0.7466453084791007

In [12]:


from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.01)
lasso_reg.fit(train_X_numeric, train_y)

lasso_reg.score(train_X_numeric, train_y)

lasso_reg.score(test_X_numeric, test_y)

0.7850812643543872

In [13]:


from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.1)
ridge_reg.fit(train_X_numeric, train_y)

ridge_reg.score(train_X_numeric, train_y)

ridge_reg.score(test_X_numeric, test_y)

from sklearn.linear_model import ElasticNet
elastic_reg = ElasticNet(alpha=0.01, l1_ratio=0.5)
elastic_reg.fit(train_X_numeric, train_y)

elastic_reg.score(train_X_numeric, train_y)

elastic_reg.score(test_X_numeric, test_y)

0.7963550279159376